### ISSUE TITLE
Añadir P Line

### ISSUE THREAD

**Issue by alexpdp7** [alexpdp7/pdp7.ddex#11]
* P LINE

```
<PLineText>
Armin Audio B.V. under exclusive license to Armada Music B.V
</PLineText>
</PLine>
```

**Comment by alexpdp7** [comment]
Esto ya estaba como Track Production Owner...

**Comment by dontplaymix** [comment]
Perdona, me acabo de dar cuenta que no te indiqué correctamente este campo.
Faltaría añadir este campo quedes el P Line del Release

<PLineText>
Blanco y Negro Music under exclusive license from Armada Music B.V.
</PLineText>
</PLine>
<CLine>
<Year>2017</Year>
<CLineText>
Blanco y Negro Music under exclusive license from Armada Music B.V.
</CLineText>
</CLine>

**Comment by alexpdp7** [comment]
https://github.com/alexpdp7/pdp7.ddex/pull/14

[release_from_zip.zip](https://github.com/alexpdp7/pdp7.ddex/files/1714294/release_from_zip.zip)

He añadido un "Release P Line" con el P Line del release tal como lo he interpretado. Te adjunto ejemplo para que veas como queda y confirmes si es lo que quieres o no.

**Comment by dontplaymix** [comment]
Ahora si :-)
