### ISSUE TITLE
Añadir columna remixer

### ISSUE THREAD

**Issue by alexpdp7** [alexpdp7/pdp7.ddex#2]
REMIXER: el XML de ejemplo que me has pasado no tiene... no sé si tienes alguno con remixer para que vea qué rol DDEX le ponen. Te mando uno por email; Recuerdo que se podían adjuntar archivos pero no recuerdo como.

**Comment by dontplaymix** [comment]
Este es uno de los remixers que hay en el DDEX

DisplayArtist>
<PartyName>
<FullName>Mike Hawkins</FullName>
</PartyName>
<ArtistRole UserDefinedValue="Remixer" Namespace="PADPIDA2010051102D">UserDefined</ArtistRole>

Básicamente el DDEX lo que hace constantemente es ir identificando los roles de las personas que aparecen en el tema (Artists Role). Así (que hoy me he enterado que asín es también correcto según la RAE), tenemos definidos roles de Primary Artists, Featured Artist, Composer, Author, Remixer...
Te vuelvo a adjuntar el xlsx  para probar que se pueden mandar adjuntos :-)
[8421597101390.xlsx](https://github.com/alexpdp7/pdp7.ddex/files/1698319/8421597101390.xlsx)
