### ISSUE TITLE
Añadir columna copyright owner

### ISSUE THREAD

**Issue by alexpdp7** [alexpdp7/pdp7.ddex#4]
* COPYRIGHT OWNER

```
<PLineText>
Armin Audio B.V. under exclusive license to Armada Music B.V
```

Siempre es: Siempre es: buscar 'license'; Si aparece, es lo que queda a la derecha de 'license to'; Si no, el valor que aparece (Blanco y Negro Music, Blanco y Negro Latino, Blanco y Negro Pop...)

**Comment by alexpdp7** [comment]
Buenas,

Con eso las conversiones que me hace son:

8bit Records ---> 8bit Records
Alessio Lazzaroni ---> Alessio Lazzaroni
ARC Records ---> ARC Records
Armada Music ---> Armada Music
Armada Music B.V. ---> Armada Music B.V.
Armada Music B.V. under exclusive license from Showland Records ---> Armada Music B.V. under exclusive license from Showland Records
Armin Audio B.V. under exclusive license to Armada Music B.V. ---> Armada Music B.V.
Axtone Records ---> Axtone Records
Axtone Records Ltd. ---> Axtone Records Ltd.
Axwell Music AB and Refune Music Ltd. Under exclusive license to Def Jam Recordings ---> Def Jam Recordings
Axwell Music AB and Refune Music Ltd. Under exclusive license to Virgin EMI records, a division of Universal Music Operations Ltd ---> Virgin EMI records, a division of Universal Music Operations Ltd
Bassa Clan ---> Bassa Clan
Blanco y Negro bajo licencia Ocesa Promotora S.A. de C.V. ---> Blanco y Negro bajo licencia Ocesa Promotora S.A. de C.V.
Blanco y Negro ---> Blanco y Negro
Blanco y Negro Music ---> Blanco y Negro Music
Blanco Y Negro Music ---> Blanco Y Negro Music
Blanco y Negro Music/Música Global Discogràfica ---> Blanco y Negro Music/Música Global Discogràfica
Blanco y Negro Music \ Musical Freedom ---> Blanco y Negro Music \ Musical Freedom
Blanco y Negro Music S.A. ---> Blanco y Negro Music S.A.
Blanco y Negro Music, S.A. ---> Blanco y Negro Music, S.A.
Blanco y Negro Music under exclusive license from Edinet s.r.l. ---> Blanco y Negro Music under exclusive license from Edinet s.r.l.
Blanco y Negro Music under exclusive License from Minifunk Records ---> Blanco y Negro Music under exclusive License from Minifunk Records
Blanco y Negro Music under exclusive license from Ross Srl - Bang Record ---> Blanco y Negro Music under exclusive license from Ross Srl - Bang Record
Blanco y Negro Music under exclusive license from Smash The House/CNR Records ---> Blanco y Negro Music under exclusive license from Smash The House/CNR Records
Blanco y Negro Music under exclusive license from Sweat It Out Music/Central Station ---> Blanco y Negro Music under exclusive license from Sweat It Out Music/Central Station
Blanco y Negro Music under exclusive license from Zooland Records ---> Blanco y Negro Music under exclusive license from Zooland Records
Bpitch Control ---> Bpitch Control
CNR ---> CNR
CNR Music Belgium N.V. ---> CNR Music Belgium N.V.
Code Red/Cloud 9 Music ---> Code Red/Cloud 9 Music
CopyrighT Control ---> CopyrighT Control
Dance & Love ---> Dance & Love
Dipiu' Srl ---> Dipiu' Srl
DJ Center ---> DJ Center
Doorn/SpinninRecords.com ---> Doorn/SpinninRecords.com
Downhill Music ---> Downhill Music
Dumping CPU usage by sampling running threads ... done.
D-Vine Sounds ---> D-Vine Sounds
Edinet ---> Edinet
Electric Bodega, LLC ---> Electric Bodega, LLC
Elevate ---> Elevate
Energy Production ---> Energy Production
Enormous Tunes, A Unit Of Gnkp Goodnight Kiss Productions Gmbh / Sirup Music Gmbh Licensed From Sirup Music Gmbh ---> Enormous Tunes, A Unit Of Gnkp Goodnight Kiss Productions Gmbh / Sirup Music Gmbh Licensed From Sirup Music Gmbh
Extravagazanza Publishing Srl ---> Extravagazanza Publishing Srl
Fanatic records ---> Fanatic records
Flamingo Recordings B.V. ---> Flamingo Recordings B.V.
Fonk Recordings/Cloud 9 Music ---> Fonk Recordings/Cloud 9 Music
Glasgow Underground Music ---> Glasgow Underground Music
Gt2 ---> Gt2
GT2 ---> GT2
Hexagon ---> Hexagon
Isgud Records ---> Isgud Records
Jacks' House Recordings ---> Jacks' House Recordings
Jus Groove It ---> Jus Groove It
Kaoz Theory ---> Kaoz Theory
Keep! ---> Keep!
Keep! Records ---> Keep! Records
Knee Deep In Sound ---> Knee Deep In Sound
Konga Musica, a label of Blanco y Negro Music under exclusive license from New Music International ---> Konga Musica, a label of Blanco y Negro Music under exclusive license from New Music International
Konga Music, a label of Blanco y Negro Music ---> Konga Music, a label of Blanco y Negro Music
Konga Music ---> Konga Music
Konga records ---> Konga records
Kontor Records ---> Kontor Records
Lentos Records ---> Lentos Records
Livelife Records, a label of Blanco y Negro Music ---> Livelife Records, a label of Blanco y Negro Music
Live Life Records ---> Live Life Records
Livetop Music/Ripmusic ---> Livetop Music/Ripmusic
Lost & Cie under exclusive license to Armada Music B.V. ---> Armada Music B.V.
Lost & Cie Under Exclusive License To Cnr Music Belgium N.v. ---> Cnr Music Belgium N.v.
Moda Black ---> Moda Black
Moon Harbour Recordings ---> Moon Harbour Recordings
Musical Freedom Label Ltd. ---> Musical Freedom Label Ltd.
Never Stop Music ---> Never Stop Music
Nonstop Music Group ---> Nonstop Music Group
Octopus Recordings ---> Octopus Recordings
Organic Music, a label of Blanco y Negro Music S.A. ---> Organic Music, a label of Blanco y Negro Music S.A.
Outburst Records ---> Outburst Records
Pacha Recordings ---> Pacha Recordings
Planet Gong Productions ---> Planet Gong Productions
Planet Phunk ---> Planet Phunk
Planet Punk Music Gmbh ---> Planet Punk Music Gmbh
Planet Punk Music GmbH ---> Planet Punk Music GmbH
Politics Of Dancing Music ---> Politics Of Dancing Music
Protocol Recordings B.V. ---> Protocol Recordings B.V.
Protocol Recordings ---> Protocol Recordings
Refune Music Ltd. Under exclusive license to Universal Music AB ---> Universal Music AB
Refune Music Rights AB ---> Refune Music Rights AB
Rejected ---> Rejected
Revealed / Cloud 9 ---> Revealed / Cloud 9
Revealed Recordings/Cloud 9 Music ---> Revealed Recordings/Cloud 9 Music
Revealed Recordings, under exclusive license to Cloud 9 Music B.V. ---> Cloud 9 Music B.V.
RLS Productions under exclusive license to Blanco y Negro by Casablanca-MCA France ---> Blanco y Negro by Casablanca-MCA France
RLS / Universal Music France ---> RLS / Universal Music France
RNC Music ---> RNC Music
Ross / Bang Record ---> Ross / Bang Record
Senzala ---> Senzala
Slave Music ---> Slave Music
Smash The House ---> Smash The House
Sound4Label Sarl ---> Sound4Label Sarl
Sound Of Pirates ---> Sound Of Pirates
Spinnin' Deep / SpinninRecords.com ---> Spinnin' Deep / SpinninRecords.com
SpinninRecords.com ---> SpinninRecords.com
Stmpd Records ---> Stmpd Records
Strange Fruits ---> Strange Fruits
Suara ---> Suara
Subside Records ---> Subside Records
Suprime Music GmbH & Co.KG ---> Suprime Music GmbH & Co.KG
System2 Records ---> System2 Records
Tanzbar Musik ---> Tanzbar Musik
Teta-Making Music, Ltd. ---> Teta-Making Music, Ltd.
Time S.p.A. ---> Time S.p.A.
Tinted Records ---> Tinted Records
Toolroom Productions ---> Toolroom Productions
Twocolors ---> Twocolors
Universal Music Polska ---> Universal Music Polska
Vendetta Records, a label of Blanco y Negro Music, under license from Arbex Music & Publishing ---> Vendetta Records, a label of Blanco y Negro Music, under license from Arbex Music & Publishing
Vendetta Records, a label of Blanco y Negro Music ---> Vendetta Records, a label of Blanco y Negro Music
Wall Recordings under exclusive license to Armada Music B.V. ---> Armada Music B.V.
WAO ---> WAO
X-Energy / Energy Production S.r.l. Under Exclusive License From Republic Of Kadebostany ---> X-Energy / Energy Production S.r.l. Under Exclusive License From Republic Of Kadebostany
Yawa Recordings Gmbh Under Exclusive License To Sprs/spinninrecords.com ---> Sprs/spinninrecords.com
Zooland Music ---> Zooland Music

, que son muy poquitas... ¿hay que hacer lo mismo pero "al revés" para el "Under Exclusive License From"? ¿"Licensed From"?

**Comment by alexpdp7** [comment]
WIP https://github.com/alexpdp7/pdp7.ddex/pull/12

**Comment by dontplaymix** [comment]
Déjalas así y ya las unificaré yo en el xls
