### ISSUE TITLE
Añadir digital release date

### ISSUE THREAD

**Issue by alexpdp7** [alexpdp7/pdp7.ddex#8]
* DIGITAL RELEASE DATE

```
<OriginalReleaseDate>2017-09-08</OriginalReleaseDate>
<OriginalDigitalReleaseDate>2017-09-08</OriginalDigitalReleaseDate>
```

**Comment by alexpdp7** [comment]
Del track o del release?

**Comment by dontplaymix** [comment]
Del release.
Ahora mismo el formato que estamos usando es mm/dd/yyyy, pero aún no sé cual tendré que usar para The Orchard. Estoy a la espera
